### ISSUE TITLE
[BUG] Error 400 for user.update, user.authorization.revoke and revokation events

### ISSUE THREAD

**Issue by dialogik** [mitchwadair/tesjs#16]
### Describe the bug

I am getting `400 Bad Request` errors for the three events `user.update`, `user.authorization.revoke` and `revokation`:

```
Error subscribing to user.authorization.revoke {
  error: 'Bad Request',
  status: 400,
  message: "unknown validation error: Key: 'SubscriptionCondition.client_id' Error:Field validation for 'client_id' failed on the 'required' tag"
}
Error subscribing to user.update {
  error: 'Bad Request',
  status: 400,
  message: "unknown validation error: Key: 'SubscriptionCondition.user_id' Error:Field validation for 'user_id' failed on the 'required' tag"
}
Error subscribing to revokation {
  error: 'Bad Request',
  status: 400,
  message: 'invalid subscription type and version'
}
```

**To Reproduce**
1. Define event handlers for all three events.
2. Subscribe to all three events.

**Expected behavior**
There should not be any errors but success messages for all three event subscriptions.

**Comment by mitchwadair** [comment]
Could you give an example of the subscriptions made for these events?  It looks like there may be issues with the conditions you used.

**Comment by dialogik** [comment]
This is how I define listeners and create subscriptions

```
// User Authorization Revoke
twitch.on('user.authorization.revoke', (clientId, userId, userLogin, userName) => {
    console.log('user.authorization.revoke', {clientId, userId, userLogin, userName});
});

// User Update
twitch.on('user.update', (userId, userLogin, userName, email, description) => {
    console.log('user.update', {userId, userLogin, userName, email, description});
});

const events = [
    // ...
    'user.authorization.revoke',
    'user.update'
];

for(const event of events) {
    // Create subscriptions
    twitch.subscribe(event, {
        broadcaster_user_id: process.env.TWITCH_BROADCASTER_ID
    }).then(_ => {
        console.log(`${event} successfully subscribed`);
    }).catch(error => {
        console.log(`Error subscribing to ${event}`, error);
    });
}
```

And thank you for the hint on the `revocation` event. Maybe the fact that there is no subscription needed should be added to [the documentation](https://github.com/mitchwadair/tesjs/blob/main/doc/events.md#subscription-revocation)?

**Comment by mitchwadair** [comment]
Yes, that is a good idea.  I should definitely make it more clear on the doc for `revocation`.  As for your subscriptions, it does look like the conditions you are using are not quite right.  Each subscription type has different condition parameters (although some are the some or have some overlap).  

For `user.authorization.revoke`, you can find it [here](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#userauthorizationrevoke) in Twitch doc.  Its condition just has `client_id` (rather than the `broadcaster_user_id` that you currently have).

For `user.update`, you can find it [here](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#userupdate).  Its condition uses `user_id`.

Unfortunately this means your current loop to subscribe to events will not work, but a small change could net you similar results!  Creating an array with objects containing your `type` and `condition` as properties would be a good solution to keep the same simplicity of using the loop.
EX:
```
const events = [
    {type: 'user.update', condition: {user_id: '1337'}},
    {type: 'user.authorization.revoke', condition: {client_id: process.env.CLIENT_ID}}
]

for(const event of events) {
    // Create subscriptions
    twitch.subscribe(event.type, event.condition).then(_ => {
        console.log(`${event.type} successfully subscribed`);
    }).catch(error => {
        console.log(`Error subscribing to ${event.type}`, error);
    });
}
```

Hopefully this helps!

**Comment by dialogik** [comment]
Thanks for clarification and the code example. That will work!
