### ISSUE TITLE
[QUESTION]Reasons to search for an appetizer for receiving a 409 error

### ISSUE THREAD

**Issue by patrickmonster** [mitchwadair/tesjs#43]
**Write your question**

Why is it necessary to search for all events and provide them to users when a subscription event occurs?

**Additional context**
Put anything that adds context to your question.  Environment, goal, etc.

https://github.com/mitchwadair/tesjs/blob/fe4a9f54874898b3c7b6f1ae96e5c3f277bc7b42/lib/tes.js#L149

When an already registered event (409error) occurs, it always searches for all events and returns the event.

If a duplicate subscription event occurs when there are all 100,000 events,
You must proceed up to 100 seeks.
Without internal caching
If multiple duplicate events occur, systemic problems may occur.
Is there any reason for this?

For those who have already registered
stream.online, stream.offline, channel.update
If an event is registered, you must perform a full search at least 3 times.

**Comment by mitchwadair** [comment]
This is kind-of tricky, and 100% subject to input/change.  The current API design for TES is that when a consumer attempts to create a subscription, they will get back the details of their subscription from the promise.  This means that if the subscription exists already and they attempt to create another one, it should still return the details of the subscription for them to use.  I do recognize this is a pretty inefficient solution to this problem, so I am definitely reconsidering that design.  The main goal for this library, in my opinion, is to stay as light-weight as possible while also providing consumers with value by reducing the work needed to work with EventSub.  For this reason, I decided to try and avoid storing too much data in memory (i.e. keeping track of all subscriptions internally).

So, as you highlighted, this all becomes a problem with high-volumes of subscriptions.  There are a lot of challenges related to how EventSub works and using/developing TES.  I think the main situation where this will occur is when restarting a TES application.  If the consumer is making a bunch of subscriptions on start-up it can become a problem quickly.  But an internal cache does not solve this issue, as that would be lost when shutting down the app.  The one optimization I currently have in place for this is using the `getSubscriptionByType` function to reduce the number of API calls being made, but that only helps so much.  Ideally, a developer should work on having a good flow for creating/deleting subscriptions that would mitigate the issue of having to search through thousands of subscriptions however.
For example, say you were working on some kind of notification service; A user might log in to your service and enable notifications for some event.  This would be the trigger to subscribe to the event for that user.  Then, later, they decide to stop getting those notifications and disable them.  This would be the trigger to unsubscribe.  There are related challenges with this as well, since you need to have a subscription id to delete/unsubscribe (and therefore do the problematic search anyways).  But this is where a developer might come up with their own way of storing/handling subscription info, like using a database or something of that sort (or even storing to a file).

So all in all, I think from a design perspective, it should probably be on the developer to maintain some store of their subscriptions in whatever way they see fit.  But that said, I do this considering design change on the part of this specific case is reasonable.  One solution we could consider is only returning subscription info on a successful subscription creation.  This would mean that if a subscription exists already and returns a 409, that TES would inform the consumer and they would handle it however they please.  I kind-of like this solution, as it puts more control into the hands of the developer rather than making opinionated decisions for them.

I am all-ears for additional suggestions or feedback so go for it if you have any.

**Comment by patrickmonster** [comment]
There doesn't seem to be any reason to return 100% of information about subscriptions.
If a 409 error occurs due to Twitch's own subscription request failure, this is not handled by the library, but the client user has to handle it, and users who want to use the library lightly by using the library agree fully on that part do.
However, the subscription form is inefficient for many library users, and it is recommended to at least give users a choice.
If many users proceed with development without recognizing that there is a corresponding part before opening the library, a problem with the web service itself occurs, and in addition to the library, the rate limit (https://dev.twitch.tv/docs/api/guide#rate-limits), I think that there may be enough possibilities.

**Comment by mitchwadair** [comment]
Yep I definitely agree. That is a good point on rate limiting as well. I think a design change should be made to be on the user to handle the errors.
