### ISSUE TITLE
[BUG] can't subscribe to raid event

### ISSUE THREAD

**Issue by TiotBenjy** [mitchwadair/tesjs#51]
**Describe the bug**
We can't subscribe to raid event

**To Reproduce**

1. subscribe to raid event and then you have the following error :

TypeError: Cannot read properties of undefined (reading '0')
    at EventManager.queueSubscription (/www/wwwroot/xxxxxxx/node_mjs/lib/events.js:49:42)
    at /www/wwwroot/bot.jesuiskristoff.fr/xxxxxx/tesjs/lib/tes.js:180:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Expected behavior**
If it is possible fix the issue

**Environment:**
- OS: UBUNTU 20.04
- Node Version [e.g. 15.3.0]: v16.15.1
- TESjs Version [e.g. 0.1.0]: "tesjs": "^0.6.2",

**Comment by mitchwadair** [comment]
Hi! Could you please show how you are subscribing to the event?

**Comment by TiotBenjy** [comment]
Yes sure ! There is the code : 

```javascript
tes.on('channel.raid', async (event) => {
       // my code when the event is triggered
});

// create a new subscription for the 'channel.raid' event for broadcaster
tes.subscribe('channel.raid', {
    broadcaster_user_id: 12345678
}).then(_ => {
    console.log("Subscribed to channel.raid event");
}).catch(err => {
    console.log("RAID SUBSCRIBE ERROR");
    console.log(err);
});
```

**Comment by mitchwadair** [comment]
Looks like your [condition for the raid subscription](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-raid-condition) is incorrect.  You'll need either `from_broadcaster_user_id` or `to_broadcaster_user_id` depending on what you are trying to accomplish with your event handler.  Let me know if that fixes your problem!

As a side note, if that is the problem, I am intending to improve intellisense on conditions with #39.  I should also probably try to improve the error handling/messaging here since it isn't immediately obvious what the source of the error is

**Comment by mitchwadair** [comment]
@TiotBenjy did this solve your problem?  I'll be closing this if it did, or if I do not hear back soon :+1:

**Comment by TiotBenjy** [comment]
Hello,

Sorry I've forgotten to reply to your comment, yes it works ! Thanks for your help.

Have a great day.

**Comment by mitchwadair** [comment]
Great! Happy to help 🙂
